# Generated by Django 5.1.1 on 2024-09-27 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('stock_producto', models.CharField(choices=[('disponible', 'Disponible'), ('no disponible', 'No disponible')], max_length=20)),
                ('tipo_producto', models.CharField(choices=[('Bebida Alcohólica', 'Bebida Alcohólica'), ('Platos a la Carta', 'Platos a la Carta'), ('Entradas', 'Entradas'), ('Box', 'Box'), ('Mesas', 'Mesas')], max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_oferta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('descripcion', models.TextField()),
                ('detalle', models.CharField(max_length=255)),
                ('marca', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('insumos', models.CharField(max_length=255)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
            ],
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
