# Generated by Django 5.1.1 on 2024-09-27 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0002_producto_delete_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='miniatura',
            field=models.ImageField(editable=False, null=True, upload_to='miniaturas/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, default='productos/default.png', null=True, upload_to='productos/'),
        ),
    ]
