# Generated by Django 5.1.1 on 2024-10-24 02:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0005_remove_producto_insumos_producto_bebidas_alcoholicas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='bebidas_alcoholicas',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='detalle',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='mesas_adicionales_precio',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='nombre_cliente',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='platos_a_la_carta',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio_oferta',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='restricciones',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock_producto',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='tipo_producto',
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(default='Sin categoría', max_length=255),
        ),
        migrations.AddField(
            model_name='producto',
            name='color',
            field=models.CharField(default='Sin color', max_length=255),
        ),
        migrations.AddField(
            model_name='producto',
            name='envio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='producto',
            name='garantia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagenes',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='producto',
            name='medidas',
            field=models.CharField(default='Sin medidas', max_length=255),
        ),
        migrations.AddField(
            model_name='producto',
            name='modelo',
            field=models.CharField(default='Sin modelo', max_length=255),
        ),
        migrations.AddField(
            model_name='producto',
            name='servicio_tecnico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='subcategoria',
            field=models.CharField(default='Sin subcategoría', max_length=255),
        ),
        migrations.AddField(
            model_name='producto',
            name='tamaño',
            field=models.CharField(default='Sin tamaño', max_length=255),
        ),
        migrations.AddField(
            model_name='producto',
            name='tiempo_entrega',
            field=models.IntegerField(choices=[(8, '8 horas'), (12, '12 horas'), (24, '24 horas'), (48, '48 horas')], default=24),
        ),
        migrations.AddField(
            model_name='producto',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(default='Sin descripción'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.CharField(default='Sin marca', max_length=255),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(default='Sin nombre', max_length=255),
        ),
    ]
